### ISSUE TITLE
Issue with Python 3.6 and Pandas

### ISSUE THREAD

**Issue by TRomijn** [matthewjwoodruff/pareto.py#30]
Not sure if I'm making a mistake or whether some function has been updated in newer versions of Python.

This is the error message I receive when trying your script in python:
"TypeError: 'map' object is not subscriptable"
and:
"TypeError: Failed to make input 0 row-iterable"

This is the code I've used. Both tested with one of the datasets on this Github as my own (smaller) dataset.
`table = pandas.read_table("Dataset.txt")`
`nondominated = pareto.eps_sort([table.itertuples(False)], [3, 4, 5], [1, 0.1, 3])`

**Comment by TRomijn** [comment]
Problem was much simpler than I thought. Adding `list()` around the itertuple function solved the problem:
`nondominated = pareto.eps_sort([list(table.itertuples(False))], [3, 4, 5], [1, 0.1, 3])`

**Comment by matthewjwoodruff** [comment]
Thanks!  I'll put a note about this in the documentation.  I suspect Pandas has changed what `itertuples` does.
